### ISSUE TITLE
Demo program not working

### ISSUE THREAD

**Issue by ajcj151** [amarpersaud/NeuralNetworkBase#1]
How I start a network with 32 inputs and 32 outputs?

**Comment by amarpersaud** [comment]
There were a few errors in it that I just fixed *and committed. The demo program was missing a reference to the project.

I added some wiki pages that you might want to take a look at

The ImgNN program part of it is not that well written (I did it a long time ago). The `Training A Network` page should help once you actually get it working

**Comment by ajcj151** [comment]
I fixed here with:

for (int j = 0; j < Layers.Length; j++)
            {
                Layers[j] = new Layer();
                if (j == Layers.Length - 1)
                {
                    Layers[j].Neurons = new Neuron[outputs];
                    Layers[j].Output = new double[outputs]; // added this ***********
                }
                else
                {
                    Layers[j].Neurons = new Neuron[neuronCount[j]];
                    Layers[j].Output = new double[neuronCount[j]]; // and this ***********
                }
